const toolList = [
  ['HTML', 'https://www.w3schools.com/html/html_intro.asp'],
  ['CSS', 'https://www.w3schools.com/html/html_css.asp'],
  ['Sass', 'https://sass-lang.com/'],
  ['Bootstrap', 'https://getbootstrap.com/'],
  ['jQuery', 'https://jquery.com/'],
  ['Handlebars.js', 'https://handlebarsjs.com/'],
  ['Node.js', 'https://nodejs.org/en/'],
  ['Express.js', 'https://expressjs.com/'],
  ['MongoDB', 'https://www.mongodb.com/'],
  ['Mongoose', 'https://mongoosejs.com/'],
  ['SQL', 'https://www.w3schools.com/sql/'],
  ['MySQL', 'https://www.mysql.com/'],
  ['PostgreSQL', 'https://www.postgresql.org/'],
  ['Sequelize', 'http://docs.sequelizejs.com/'],
  ['React', 'https://reactjs.org/'],
  ['React-Router', 'https://reacttraining.com/react-router/'],
  ['Redux', 'https://redux.js.org/'],
  ['Moment.js', 'https://momentjs.com/'],
  ['Cheerio', 'https://cheerio.js.org/'],
  ['JWT', 'https://jwt.io/'],
  ['Webpack', 'https://webpack.js.org/'],
  ['Babel', 'https://babeljs.io/'],
  ['Heroku', 'https://www.heroku.com/'],
]

export default toolList
